### ISSUE TITLE
顺序执行2次 FFmpegCommand.runCmd 会报错

### ISSUE THREAD

**Issue by linfeizheng** [AnJoiner/FFmpegCommand#46]
我先对file1进行裁剪，得到结果file3后和file2进行拼接操作，会报错

    Process: voicerecorder.audiorecorder.voice, PID: 867
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.coder.ffmpeg.jni.FFmpegCmd.onError(FFmpegCmd.kt:205)

**Comment by linfeizheng** [comment]
FFmpegCmd的onComplete方法，mCallbacks只要size>1，就不能用这种方式remove数据

**Comment by linfeizheng** [comment]
描述清楚一点，是在裁剪的onComplete里进行合并命令
